In [1]:
from demoparser2 import DemoParser

parser = DemoParser("demos/demo1.dem")
print(parser)

<builtins.DemoParser object at 0x000001F719A7B570>

In [2]:
events = parser.list_game_events()
print(events)

['cs_round_start_beep', 'decoy_detonate', 'buytime_ended', 'weapon_reload', 'player_connect_full', 'weapon_fire', 'round_announce_last_round_half', 'hltv_versioninfo', 'other_death', 'decoy_started', 'inferno_startburn', 'round_prestart', 'bomb_beginplant', 'player_hurt', 'bomb_dropped', 'player_footstep', 'bomb_planted', 'smokegrenade_detonate', 'weapon_zoom', 'player_death', 'smokegrenade_expired', 'round_announce_match_point', 'player_spawn', 'show_survival_respawn_status', 'flashbang_detonate', 'bomb_exploded', 'announce_phase_end', 'server_cvar', 'item_equip', 'player_blind', 'player_disconnect', 'begin_new_match', 'round_announce_warmup', 'bomb_pickup', 'item_pickup', 'chat_message', 'round_time_warning', 'hegrenade_detonate', 'cs_pre_restart', 'round_officially_ended', 'fire_bullets', 'player_team', 'inferno_expire', 'round_announce_match_start', 'player_connect', 'round_freeze_end', 'round_poststart', 'cs_win_panel_match', 'cs_round_final_beep']

In [3]:
blind_df = parser.parse_event("player_blind")
blind_df

,attacker_name,attacker_steamid,blind_duration,entityid,tick,user_name,user_steamid
0,Goreer,76561198141043173,0.828735,531,14307,Goreer,76561198141043173
1,speK_777,76561198232609388,0.615339,307,14509,speK_777,76561198232609388
2,olix3,76561198197319005,2.624660,474,14691,HiddenKinng,76561198419846636
3,HiddenKinng,76561198419846636,4.154967,391,19098,HiddenKinng,76561198419846636
4,Goreer,76561198141043173,0.589538,457,19212,Goreer,76561198141043173
...,...,...,...,...,...,...,...
102,Zqyrzov,76561199706772780,1.256252,874,111364,Goreer,76561198141043173
103,olix3,76561198197319005,3.581107,477,111493,feryrenifery,76561198227808868
104,olix3,76561198197319005,0.998545,477,111493,stathamJR,76561199783959393
105,olix3,76561198197319005,4.486316,477,111493,Zqyrzov,76561199706772780
106,olix3,76561198197319005,1.045024,477,111493,Sriajj,76561199562905829

In [4]:
print(blind_df.shape)
print(blind_df.dtypes)

(107, 7)
attacker_name           str
attacker_steamid        str
blind_duration      float32
entityid              int32
tick                  int32
user_name               str
user_steamid            str
dtype: object

In [5]:
flashes = blind_df.groupby(["entityid", "tick"]).size()
flashes

entityid  tick
120       50842     2
166       74884     1
203       107318    3
212       49223     1
215       59163     1
220       84808     2
229       20767     1
239       20958     2
286       48753     2
307       14509     1
348       54452     1
359       26987     2
365       100482    3
368       84885     4
391       19098     1
          84747     4
393       100712    4
423       107163    2
457       19212     1
474       14691     1
477       111493    4
480       48485     2
497       26260     1
503       59581     1
522       58734     2
531       14307     1
542       98069     1
584       40037     2
587       33295     4
615       34033     5
617       108091    2
663       95127     1
727       39641     2
738       36053     1
744       67542     2
783       20824     2
793       26413     3
810       33258     3
862       24094     2
870       27337     1
873       67528     2
874       111364    3
885       34085     7
890       78459     2
901       103542    1
914       96389     2
950       73282     1
958       107661    3
972       33090     4
994       39053     1
dtype: int64

In [6]:
print("Rows in blind.df:", len(blind_df))
print("Actual flashes:", len(flashes))

Rows in blind.df: 107
Actual flashes: 50

In [7]:
detonate_df = parser.parse_event("flashbang_detonate")
detonate_df

,entityid,tick,user_name,user_steamid,x,y,z
0,531,14307,Goreer,76561198141043173,-997.288757,314.030273,-353.214813
1,307,14509,speK_777,76561198232609388,-780.477966,-957.882080,-156.740036
2,474,14691,olix3,76561198197319005,-857.141602,-52.230400,-156.070587
3,853,18950,HiddenKinng,76561198419846636,-489.498596,-416.709137,459.440002
4,391,19098,HiddenKinng,76561198419846636,-119.935860,-782.883728,-219.372925
5,457,19212,Goreer,76561198141043173,-990.273682,308.351685,-354.226532
6,229,20767,olix3,76561198197319005,-186.314117,-1842.659302,229.567047
7,783,20824,demalshh,76561198976015863,-51.922565,-1673.379395,-142.721817
8,239,20958,4otam667,76561198929872063,40.985703,-1823.573242,7.771549
9,986,21733,speK_777,76561198232609388,-1400.067627,-2506.176514,-96.807747
10,862,24094,olix3,76561198197319005,-661.262085,-909.999817,-225.089493
11,497,26260,HiddenKinng,76561198419846636,-464.850311,-244.258606,147.048447
12,793,26413,HiddenKinng,76561198419846636,491.147705,-902.096069,130.780716
13,359,26987,olix3,76561198197319005,-876.286072,-114.805977,-160.692902
14,870,27337,speK_777,76561198232609388,-812.811646,-88.341743,-156.265976
15,972,33090,HiddenKinng,76561198419846636,184.870865,-1530.973511,264.365936
16,810,33258,Goreer,76561198141043173,36.750973,-1604.146118,259.085693
17,587,33295,olix3,76561198197319005,-488.273041,-1837.760376,526.303528
18,615,34033,olix3,76561198197319005,-197.710876,-1972.617310,-152.923553
19,885,34085,4otam667,76561198929872063,-561.444397,-2279.578613,-5.275510
20,738,36053,stathamJR,76561199783959393,-627.088135,-1918.609741,-166.075439
21,994,39053,Goreer,76561198141043173,-979.550720,308.221771,-349.987335
22,727,39641,Sriajj,76561199562905829,-1224.512329,668.120605,-76.890869
23,584,40037,stathamJR,76561199783959393,-994.578430,-346.160187,-344.457336
24,467,47737,HiddenKinng,76561198419846636,128.560272,-1418.829102,131.735214
25,144,48221,HiddenKinng,76561198419846636,129.987137,-1420.220215,132.409439
26,480,48485,stathamJR,76561199783959393,100.228806,-1469.343384,-170.894104
27,286,48753,speK_777,76561198232609388,306.806641,-1601.511108,383.846008
28,212,49223,4otam667,76561198929872063,41.993870,-1829.346191,16.441097
29,120,50842,4otam667,76561198929872063,43.320396,-1828.076660,14.921006
30,641,53659,HiddenKinng,76561198419846636,-572.355896,-443.353973,220.657944
31,348,54452,speK_777,76561198232609388,-856.709290,-100.860252,-158.783112
32,522,58734,Sriajj,76561199562905829,-849.301819,-702.029419,-257.167389
33,215,59163,olix3,76561198197319005,-662.468811,-1509.964233,-164.948212
34,503,59581,4otam667,76561198929872063,-726.521057,-1308.248657,-112.329552
35,873,67528,stathamJR,76561199783959393,-500.441559,-1725.871216,-103.982643
36,744,67542,4otam667,76561198929872063,42.849751,-1828.762939,15.808666
37,950,73282,stathamJR,76561199783959393,-984.012085,-793.271973,-259.547394
38,166,74884,demalshh,76561198976015863,48.729099,-1607.092773,-41.494858
39,890,78459,stathamJR,76561199783959393,-1087.579590,-781.516357,-261.968750
40,391,84747,stathamJR,76561199783959393,-67.141846,-2080.963379,871.038879
41,220,84808,demalshh,76561198976015863,283.521362,-1520.937256,247.287994
42,368,84885,demalshh,76561198976015863,285.952759,-1522.302490,247.935303
43,1021,89475,demalshh,76561198976015863,-1782.897461,513.336853,338.095642
44,663,95127,Goreer,76561198141043173,298.437653,-1627.366211,-159.306808
45,914,96389,stathamJR,76561199783959393,-54.766136,-2139.872559,780.682129
46,542,98069,demalshh,76561198976015863,-197.736115,-1965.943359,-148.250809
47,713,100379,Zqyrzov,76561199706772780,-570.331970,-334.004578,212.218719
48,365,100482,stathamJR,76561199783959393,175.307556,-931.313049,-151.524429
49,393,100712,HiddenKinng,76561198419846636,153.420761,-298.549316,293.589844
50,901,103542,Goreer,76561198141043173,-1069.449585,248.734406,-96.175858
51,423,107163,stathamJR,76561199783959393,210.017639,-1473.632690,207.836700
52,203,107318,stathamJR,76561199783959393,211.480896,-1469.183350,209.860565
53,958,107661,demalshh,76561198976015863,6.364466,-1372.643311,218.350281
54,617,108091,Sriajj,76561199562905829,-950.142334,-1493.938110,-69.870895
55,372,111167,4otam667,76561198929872063,-596.029663,-391.783600,253.886139
56,874,111364,Zqyrzov,76561199706772780,123.605850,-1415.006836,122.096039
57,477,111493,olix3,76561198197319005,-53.475876,-1416.625732,-27.140732
58,177,114374,demalshh,76561198976015863,271.004944,-1359.543579,167.909332

In [8]:
print("Flashes detonated:", len(detonate_df))
print("Flashes that blinded someone:", len(flashes))

Flashes detonated: 59
Flashes that blinded someone: 50

In [9]:
detonated = (set(zip(detonate_df["entityid"], detonate_df["tick"])))
blinded = (set(zip(blind_df["entityid"], blind_df["tick"])))

print("Detonated flashes = ", len(detonated))
print("Blinded flashes = ", len(blinded))
print("Flashes that detonated but didn't blind anyone:", len(detonated - blinded))

Detonated flashes =  59
Blinded flashes =  50
Flashes that detonated but didn't blind anyone: 9

In [10]:
blind_df = parser.parse_event("player_blind", player=["team_num"])
blind_df.head(10)

,attacker_name,attacker_steamid,attacker_team_num,blind_duration,entityid,tick,user_name,user_steamid,user_team_num
0,Goreer,76561198141043173,2,0.828735,531,14307,Goreer,76561198141043173,2
1,speK_777,76561198232609388,2,0.615339,307,14509,speK_777,76561198232609388,2
2,olix3,76561198197319005,2,2.624660,474,14691,HiddenKinng,76561198419846636,2
3,HiddenKinng,76561198419846636,2,4.154967,391,19098,HiddenKinng,76561198419846636,2
4,Goreer,76561198141043173,2,0.589538,457,19212,Goreer,76561198141043173,2
5,olix3,76561198197319005,2,3.419345,229,20767,demalshh,76561198976015863,3
6,demalshh,76561198976015863,3,0.758293,783,20824,feryrenifery,76561198227808868,2
7,demalshh,76561198976015863,3,0.689012,783,20824,olix3,76561198197319005,2
8,4otam667,76561198929872063,3,1.789989,239,20958,speK_777,76561198232609388,2
9,4otam667,76561198929872063,3,1.482519,239,20958,demalshh,76561198976015863,3

In [11]:
import numpy as np

conditions = [
    blind_df["attacker_steamid"] == blind_df["user_steamid"],
    blind_df["attacker_team_num"] == blind_df["user_team_num"],
]

outcomes = ["self", "team", ]

blind_df["flash_type"] = np.select(conditions, outcomes, default="enemy")
blind_df["flash_type"].value_counts()

flash_type
enemy    48
team     42
self     17
Name: count, dtype: int64

In [12]:

import pandas as pd

flash_summary = pd.crosstab(
    index = [blind_df["entityid"], blind_df["tick"]],
    columns = blind_df["flash_type"],
)

flash_summary.head(10)

flash_type       enemy  self  team
entityid tick
120      50842       2     0     0
166      74884       1     0     0
203      107318      1     0     2
212      49223       0     0     1
215      59163       0     1     0
220      84808       2     0     0
229      20767       1     0     0
239      20958       1     0     1
286      48753       1     0     1
307      14509       0     1     0

In [13]:
print(flash_summary.shape)

(50, 3)

In [14]:
flash_summary["effective"] = flash_summary["enemy"] > 0
flash_summary["effective"].head(10)

entityid  tick
120       50842      True
166       74884      True
203       107318     True
212       49223     False
215       59163     False
220       84808      True
229       20767      True
239       20958      True
286       48753      True
307       14509     False
Name: effective, dtype: bool

In [15]:
thrower = blind_df.groupby(["entityid", "tick"])["attacker_name"].first()
thrower.head()

entityid  tick
120       50842      4otam667
166       74884      demalshh
203       107318    stathamJR
212       49223      4otam667
215       59163         olix3
Name: attacker_name, dtype: str

In [16]:
flash_summary["thrower"] = thrower
flash_summary.head(10)

flash_type       enemy  self  team  effective    thrower
entityid tick
120      50842       2     0     0       True   4otam667
166      74884       1     0     0       True   demalshh
203      107318      1     0     2       True  stathamJR
212      49223       0     0     1      False   4otam667
215      59163       0     1     0      False      olix3
220      84808       2     0     0       True   demalshh
229      20767       1     0     0       True      olix3
239      20958       1     0     1       True   4otam667
286      48753       1     0     1       True   speK_777
307      14509       0     1     0      False   speK_777

In [17]:
detonate_df.columns

Index(['entityid', 'tick', 'user_name', 'user_steamid', 'x', 'y', 'z'], dtype='str')

In [18]:
wasted = detonated - blinded

detonate_indexed = detonate_df.set_index(["entityid", "tick"])
wasted_rows = detonate_indexed.loc[list(wasted)]

missing = pd.DataFrame(index=wasted_rows.index)
missing["enemy"] = 0
missing["self"] = 0
missing["team"] = 0
missing["effective"] = False
missing["thrower"] = wasted_rows["user_steamid"]

all_flashes = pd.concat([flash_summary, missing])

print(all_flashes.shape)

(59, 5)

In [19]:
report = all_flashes.groupby("thrower").agg(
    flashes_thrown = ("effective", "size"),
    effective = ("effective", "sum")
)

report["wasted"] = report["flashes_thrown"] - report["effective"]
report["waste_rate"] = (report["wasted"] / report["flashes_thrown"] * 100).round(1)

report = report.sort_values("waste_rate", ascending=False)
report

                   flashes_thrown  effective  wasted  waste_rate
thrower
76561198232609388               1          0       1       100.0
76561198419846636               4          0       4       100.0
76561198976015863               2          0       2       100.0
76561198929872063               1          0       1       100.0
76561199706772780               1          0       1       100.0
speK_777                        4          1       3        75.0
olix3                           8          4       4        50.0
Goreer                          6          3       3        50.0
HiddenKinng                     5          3       2        40.0
stathamJR                      11          9       2        18.2
4otam667                        6          5       1        16.7
demalshh                        6          5       1        16.7
Zqyrzov                         1          1       0         0.0
Sriajj                          3          3       0         0.0

In [20]:
# One clean lookup: every flash's thrower steamid, from the table that has all 59
thrower_lookup = detonate_df.groupby(["entityid", "tick"])["user_steamid"].first()

# Overwrite thrower on the full table, aligned by (entityid, tick) index
all_flashes["thrower"] = thrower_lookup

# Check: how many unique throwers now?
print(all_flashes["thrower"].nunique())
all_flashes["thrower"].isna().sum()

9

np.int64(0)

In [21]:
report = all_flashes.groupby("thrower").agg(
    flashes_thrown=("effective", "size"),
    effective=("effective", "sum")
)

report["wasted"] = report["flashes_thrown"] - report["effective"]
report["waste_rate"] = (report["wasted"] / report["flashes_thrown"] * 100).round(1)

report = report.sort_values("waste_rate", ascending=False)
report

                   flashes_thrown  effective  wasted  waste_rate
thrower
76561198232609388               5          1       4        80.0
76561198419846636               9          3       6        66.7
76561198141043173               6          3       3        50.0
76561198197319005               8          4       4        50.0
76561199706772780               2          1       1        50.0
76561198976015863               8          5       3        37.5
76561198929872063               7          5       2        28.6
76561199783959393              11          9       2        18.2
76561199562905829               3          3       0         0.0

In [22]:
names = blind_df.groupby("attacker_steamid")["attacker_name"].first()

report.index = report.index.map(names)
report

             flashes_thrown  effective  wasted  waste_rate
thrower
speK_777                  5          1       4        80.0
HiddenKinng               9          3       6        66.7
Goreer                    6          3       3        50.0
olix3                     8          4       4        50.0
Zqyrzov                   2          1       1        50.0
demalshh                  8          5       3        37.5
4otam667                  7          5       2        28.6
stathamJR                11          9       2        18.2
Sriajj                    3          3       0         0.0

In [23]:
deaths_df = parser.parse_event("player_death", player=["team_num"])
deaths_df.head(10)

,assistedflash,assister_name,assister_steamid,assister_team_num,attacker_name,attacker_steamid,attacker_team_num,attackerblind,attackerinair,distance,...,thrusmoke,tick,user_name,user_steamid,user_team_num,weapon,weapon_fauxitemid,weapon_itemid,weapon_originalowner_xuid,wipe
0,False,NaN,NaN,NaN,Sriajj,76561199562905829,2,False,False,1.384096,...,False,1989,speK_777,76561198232609388,3,knife_t,17293822569102704699,0,,0
1,False,HiddenKinng,76561198419846636,3.0,Goreer,76561198141043173,3,False,False,0.936462,...,False,2049,stathamJR,76561199783959393,2,knife,17293822569102704682,0,,0
2,False,Sriajj,76561199562905829,2.0,4otam667,76561198929872063,2,False,False,1.702634,...,False,2113,Goreer,76561198141043173,3,knife_t,17293822569102704699,0,,0
3,False,stathamJR,76561199783959393,2.0,Sriajj,76561199562905829,2,False,False,1.232096,...,False,2268,HiddenKinng,76561198419846636,3,knife_t,17293822569102704699,0,,0
4,False,NaN,NaN,NaN,olix3,76561198197319005,3,False,False,0.893058,...,False,2348,Zqyrzov,76561199706772780,2,knife_widowmaker,17293822569129509387,51414164119,,0
5,False,NaN,NaN,NaN,feryrenifery,76561198227808868,3,False,False,1.516139,...,False,2420,4otam667,76561198929872063,2,knife,17293822569102704682,0,,0
6,False,4otam667,76561198929872063,2.0,Sriajj,76561199562905829,2,False,False,1.453719,...,False,2471,feryrenifery,76561198227808868,3,knife_t,17293822569102704699,0,,0
7,False,Sriajj,76561199562905829,2.0,demalshh,76561198976015863,2,False,False,1.239538,...,False,2648,olix3,76561198197319005,3,knife_t,17293822569102704699,0,,0
8,False,NaN,NaN,NaN,Goreer,76561198141043173,2,False,False,16.255537,...,False,9990,stathamJR,76561199783959393,3,glock,17293822569112666116,49812845798,,0
9,False,olix3,76561198197319005,2.0,speK_777,76561198232609388,2,False,False,12.559731,...,False,10186,Sriajj,76561199562905829,3,glock,17293822569155067908,40415637860,,0

In [24]:
enemy_blinds = blind_df[blind_df["flash_type"] == "enemy"].copy()

flash_events = enemy_blinds.groupby(["entityid", "tick"]).agg(
    flasher_team = ("attacker_team_num", "first"),
    enemy_team = ("user_team_num", "first")
).reset_index()

flash_events.head(10)

   entityid    tick  flasher_team  enemy_team
0       120   50842             3           2
1       166   74884             3           2
2       203  107318             2           3
3       220   84808             2           3
4       229   20767             2           3
5       239   20958             3           2
6       286   48753             2           3
7       365  100482             2           3
8       368   84885             2           3
9       391   84747             2           3

In [25]:
parser.parse_header()

{'allow_clientside_entities': 'true',
 'patch_version': '14165',
 'demo_version_guid': '8e9d71ab-04a1-4c01-bb61-acfede27c046',
 'server_name': 'FACEIT.com register to play here',
 'allow_clientside_particles': 'true',
 'game_directory': '/home/hz10749/cs2/game/csgo',
 'demo_file_stamp': 'PBDEMS2\x00',
 'client_name': 'SourceTV Demo',
 'addons': '',
 'map_name': 'de_mirage',
 'fullpackets_version': '2',
 'demo_version_name': 'valve_demo_2'}

In [26]:
TICKRATE = 64
WINDOW_SECONDS = 3
WINDOW_TICKS = TICKRATE * WINDOW_SECONDS   # 192

In [27]:
test_flash = flash_events.iloc[0]
print(test_flash)

entityid          120
tick            50842
flasher_team        3
enemy_team          2
Name: 0, dtype: int64

In [28]:
# The four conditions, applied across ALL kills at once
converted = deaths_df[
    (deaths_df["attacker_team_num"] == test_flash["flasher_team"]) &
    (deaths_df["user_team_num"] == test_flash["enemy_team"]) &
    (deaths_df["tick"] > test_flash["tick"]) &
    (deaths_df["tick"] <= test_flash["tick"] + WINDOW_TICKS)
]

converted

,assistedflash,assister_name,assister_steamid,assister_team_num,attacker_name,attacker_steamid,attacker_team_num,attackerblind,attackerinair,distance,...,thrusmoke,tick,user_name,user_steamid,user_team_num,weapon,weapon_fauxitemid,weapon_itemid,weapon_originalowner_xuid,wipe
50,False,NaN,NaN,NaN,4otam667,76561198929872063,3,False,False,13.462825,...,False,50979,HiddenKinng,76561198419846636,2,mp9,17293822569102704674,0,,0

In [29]:
def did_convert(flash):
    matching_kills = deaths_df[
        (deaths_df["attacker_team_num"] == flash["flasher_team"]) &
        (deaths_df["user_team_num"] == flash["enemy_team"]) &
        (deaths_df["tick"] > flash["tick"]) &
        (deaths_df["tick"] <= flash["tick"] + WINDOW_TICKS)
    ]
    return len(matching_kills) > 0

In [30]:
flash_events["converted"] = flash_events.apply(did_convert, axis=1)
flash_events.head(10)

   entityid    tick  flasher_team  enemy_team  converted
0       120   50842             3           2       True
1       166   74884             3           2       True
2       203  107318             2           3      False
3       220   84808             2           3       True
4       229   20767             2           3      False
5       239   20958             3           2       True
6       286   48753             2           3      False
7       365  100482             2           3      False
8       368   84885             2           3       True
9       391   84747             2           3      False

In [32]:
print("Total flashes:", len(flash_events))
print("Effective flashes that converted to a kill:", flash_events["converted"].sum())

Total flashes: 34
Effective flashes that converted to a kill: 15

In [33]:
enemy_flashes = len(flash_events)            # blinded ≥1 enemy
some_blind = len(flash_summary)              # blinded ≥1 anyone
detonated = len(detonate_df)                 # all flashes

print("Detonated:", detonated)
print("Blinded someone:", some_blind)
print("Blinded an enemy:", enemy_flashes)
print()
print("Blinded nobody:", detonated - some_blind)
print("Blinded only friendly/self (no enemy):", some_blind - enemy_flashes)

Detonated: 59
Blinded someone: 50
Blinded an enemy: 34

Blinded nobody: 9
Blinded only friendly/self (no enemy): 16

In [34]:
# thrower_lookup is indexed by (entityid, tick); turn it into a small table to merge
thrower_table = thrower_lookup.reset_index()
thrower_table.columns = ["entityid", "tick", "thrower"]

flash_events = flash_events.merge(thrower_table, on=["entityid", "tick"], how="left")
flash_events.head()

   entityid    tick  flasher_team  enemy_team  converted            thrower
0       120   50842             3           2       True  76561198929872063
1       166   74884             3           2       True  76561198976015863
2       203  107318             2           3      False  76561199783959393
3       220   84808             2           3       True  76561198976015863
4       229   20767             2           3      False  76561198197319005

In [35]:
conversion_report = flash_events.groupby("thrower").agg(
    enemy_flashes=("converted", "size"),
    converted=("converted", "sum")
)
conversion_report["conversion_rate"] = (
    conversion_report["converted"] / conversion_report["enemy_flashes"] * 100
).round(1)

# swap steamids for names
conversion_report.index = conversion_report.index.map(names)
conversion_report.sort_values("conversion_rate", ascending=False)

             enemy_flashes  converted  conversion_rate
thrower
4otam667                 5          5            100.0
demalshh                 5          4             80.0
stathamJR                9          3             33.3
Sriajj                   3          1             33.3
HiddenKinng              3          1             33.3
olix3                    4          1             25.0
Goreer                   3          0              0.0
speK_777                 1          0              0.0
Zqyrzov                  1          0              0.0

In [39]:
# Total flashes thrown per player
thrown = all_flashes.groupby("thrower").size()

enemy_hit = flash_events.groupby("thrower")["converted"].agg(["size", "sum"])
enemy_hit.columns = ["enemy_flashes", "converted"]

#Combine
funnel = enemy_hit.join(thrown.rename("total_thrown"), how="right")
funnel = funnel.fillna(0)

#Reordering everything
funnel["total_thrown"] = funnel["total_thrown"].astype(int)
funnel["enemy_flashes"] = funnel["enemy_flashes"].astype(int)
funnel["converted"] = funnel["converted"].astype(int)
funnel["enemy_hit_rate"] = (funnel["enemy_flashes"] / funnel["total_thrown"] * 100).round(1)
funnel["convert_rate_of_thrown"]= (funnel["converted"] / funnel["total_thrown"] * 100).round(1)

funnel.index = funnel.index.map(names)
funnel.sort_values("convert_rate_of_thrown", ascending=False)

,enemy_flashes,converted,total_thrown,enemy_hit_rate,convert_rate_of_thrown
thrower,,,,,
4otam667,5,5,7,71.4,71.4
demalshh,5,4,8,62.5,50.0
Sriajj,3,1,3,100.0,33.3
stathamJR,9,3,11,81.8,27.3
olix3,4,1,8,50.0,12.5
HiddenKinng,3,1,9,33.3,11.1
Goreer,3,0,6,50.0,0.0
speK_777,1,0,5,20.0,0.0
Zqyrzov,1,0,2,50.0,0.0